<a href="https://colab.research.google.com/github/rishmac1/RISHIKA1/blob/main/assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=int(input("enter a number of elements to be printed in the series: "))
b=0
c=1
for x in range(1,a+1):
   print(b)
   d=b+c
   b=c
   c=d

enter a number of elements to be printed in the series: 10
0
1
1
2
3
5
8
13
21
34


In [ ]:
def fib(a):
  if a<=1:
    return a
  else:
    return fib(a-1)+fib(a-2)
a=int(input("enter a number of elements to be printed in the series: "))
for i in range(0,a):
  print(fib(i))

enter a number of elements to be printed in the series: 10
0
1
1
2
3
5
8
13
21
34


In [ ]:
n=int(input("enter a position of element to be printed in the series: "))
fib= lambda n:n if n<=1 else fib(n-1)+fib(n-2)
print(fib(n-1))



enter a position of element to be printed in the series: 10
34


In [ ]:
def get_permutation(string, i=0):
  if i == len(string):
    print("".join(string))
  for j in range(i, len(string)):
    words = [c for c in string]
    words[i], words[j] = words[j], words[i]
    get_permutation(words, i + 1)
print(get_permutation('abc'))

abc
acb
bac
bca
cba
cab
None


In [ ]:
n=int(input("Enter a positive number: "))
flag=0
if n<=1:
  flag=1
else:
  for i in range(2,n):
    if n%i==0:
      flag=1
if flag==0:
  print("prime number")
else:
  print("not a prime number")

Enter a positive number: 25
not a prime number


In [ ]:
import pandas as pd
import numpy as np

column=['a','b','c','d','e']
index=['A','B','C','D','E']
df1 = pd.DataFrame(np.random.rand(5,5),
           columns=column, index=index)
column=['e','a','b','c','d']
print(df1.reindex(column, axis='columns'))

          e         a         b         c         d
A  0.129121  0.270779  0.720392  0.308271  0.640020
B  0.240170  0.153284  0.323362  0.817118  0.336770
C  0.243578  0.138480  0.413071  0.691979  0.651940
D  0.569280  0.634902  0.320607  0.251694  0.279106
E  0.648459  0.259887  0.067420  0.216236  0.243624


In [ ]:
import pandas as pd
students = [['jackma', 34, 'Sydeny', 'Australia'],
            ['Ritika', 30, 'Delhi', 'India'],
            ['Vansh', 31, 'Delhi', 'India'],
            ['Nany', 32, 'Tokyo', 'Japan'],
            ['May', 16, 'New York', 'US'],
            ['Michael', 17, 'las vegas', 'US']]
df = pd.DataFrame(students,
                  columns=['Name', 'Age', 'City', 'Country'],
                  index=['a', 'b', 'c', 'd', 'e', 'f'])
dic={"jackma":'85%','Ritika': '90%','Vansh': '75%','Nany': '35%','May': '60%','Michael': '80%'}
df["Percentage"]=df["Name"].map(dic)
print(df)

{'jackma': '85%', 'Ritika': '90%', 'Vansh': '75%', 'Nany': '35%', 'May': '60%', 'Michael': '80%'}
      Name  Age       City    Country Percentage
a   jackma   34     Sydeny  Australia        85%
b   Ritika   30      Delhi      India        90%
c    Vansh   31      Delhi      India        75%
d     Nany   32      Tokyo      Japan        35%
e      May   16   New York         US        60%
f  Michael   17  las vegas         US        80%


In [ ]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
n= int(n_array.shape[0])
print("Numpy Matrix is:")
print(n_array)
det = np.linalg.det(n_array)
print("\nDeterminant of given", n, "X" ,n, "square matrix:")
print(int(det))

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Determinant of given 3 X 3 square matrix:
137180
