<a href="https://colab.research.google.com/github/rishmac1/RISHIKA1/blob/main/HAAI_intro_to_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AI4ICPS Hands on AI (HAAI) 2023**



## **Introduction to Python**

**Instructions:**
1. Go to file option on the menu bar and select 'Make a copy in Drive'
2. Edit and run codes on the copied file.

In case of any doubts, feel free to clarify

**Topics we will cover today:**
1. Basic data types and structures
2. Functions and Classes
3. Basics of numpy arrays
4. Basics of Pandas library
5. Basics of Matplotlib

**Section 1**. Basic Data types

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
a = True
print(type(a))
b = "abc"
print(type(b))

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'str'>


In [ ]:
b = "123"

In [ ]:
type(b)

str

**Section 1.1** Operations on basic datatypes

In [ ]:
# print(x + 1)
# print(x > 1)
print(x)
# print(x * 2)
# print(x ** 2)
# print(7 / 2)
# print(7 // 2)
x = 3
print(x == True)
print(a == True)

1
False
True


= and ==
= is an assignment

x = 6

== is used for comparison

x = 6
and y =7

print(x ==y

In [ ]:
x = 6
y = 9
print(x==y)

# * operation is multiplication
# x^2 ** is the exponential operation

print(x**1.2)

## **Section 2**. In-built data structures

##  Lists

In [ ]:
xs = [3, 1, 2, 3, 9, 10, 89]    # Create a list
# xs
# print(xs[0])
# print(xs, xs[2])  # Prints "[3, 1, 2] 2"
# print(xs[-1])     # Negative indices count from the end of the list; prints "2"
# print(type(xs[0]))

# print("**************")

# xs[-3] = 'rakshith'     # Lists can contain elements of different types
# print(xs)
# print(type(xs[-3]))
# print("*****")

# xs.append('bar')  # Add a new element to the end of the list
# print(xs)
# x = xs.pop()      # Remove and return the last element of the list
# print(x)
# print(xs)

print(len(xs))
#count() -> returns the number of times a value repeats inside the list

## List slicing

In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums[:2])
print(nums)              # Prints "[0, 1, 2, 3, 4]"
# print(nums[1:4:2])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
# print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
# print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
# nums[9:12] = [8, 9,10]        # Assign a new sublist to a slice
# print(nums)
# print(nums[7])

[0, 1]
[0, 1, 2, 3, 4]
[2, 3, 4]
[0, 1, 2, 3]


In [ ]:
print(nums[1:4])

[1, 2, 3]


In [ ]:
print(nums[1:4:2])

[1, 3]


### Loops

In [ ]:
animals = ['cat', 'dog', 'monkey']
for x in animals:
  print(x)



# print("********************************")

animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx, animal))

cat
dog
monkey
#0: cat
#1: dog
#2: monkey


In [ ]:
nums = [0,1,2,3,4, 'string1']
for i in nums:
  print(i)

print("******************")
for idx, elem in enumerate(nums):
  print(idx, elem)

0
1
2
3
4
string1
******************
0 0
1 1
2 2
3 3
4 4
5 string1


In [ ]:
l = ['a','b','c','d','e']
for i in l:
  print(i)

a
b
c
d
e


### List comprehensions

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


## **B.** Tuples

In [ ]:
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(t[0])       # Prints "5"

list_a = [(5,6),(3,7),[1,2,3,4,5],(2,3),'abcd']
list_a




<class 'tuple'>
5


[(5, 6), (3, 7), [1, 2, 3, 4, 5], (2, 3), 'abcd']

In [ ]:
l = [('ashraf',29), ('Rakshith',26)]

## **C.** Dictionaries

Key-value pair.
Keys are all unique.
{0:1, 1:2, 2:3}

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['dog'])       # Get an entry from a dictionary; prints "cute"
print(d.get('cat'))

print("************")
print('mat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary

print(d)

# print("******")
# d.pop('fish')
# print(d)

# del d['cat']
# print(d)


# print(d['fish'])      # Prints "wet"
# # print(d['monkey'])  # KeyError: 'monkey' not a key of d
# print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
# print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
# del d['fish']         # Remove an element from a dictionary
# print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

furry
cute
************
False
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}


In [ ]:
#{0:0, 1:1,2:4,3:9,4:16,5:25} ->

Loops

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

print("*******************************")

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

print("******************************")



A person has 2 legs
A cat has 4 legs
A spider has 8 legs
*******************************
A person has 2 legs
A cat has 4 legs
A spider has 8 legs
******************************


Dictionary comprehension

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


## **D.** Sets

Introduction to sets

In [ ]:
animals = {'cat', 'dog'}

# print('cat' in animals)   # Check if an element is in a set; prints "True"
# print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
# print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
# print(len(animals))       # Prints "3"
# animals.remove('cat')     # Remove an element from a set
# print(len(animals))       # Prints "2"
animals.add('mouse')
animals.add('elephant')
animals.add('zebra')
print(animals)

True
{'dog', 'mouse', 'cat', 'zebra', 'elephant', 'fish'}


In [ ]:
animals.add('cat')
print(animals)

Loops

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

Set comprehension

In [ ]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

## **Section 3.** Functions

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-2, -4, 0]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
negative
zero


In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

## **Section  4**. Classes

In [ ]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


## **Section 5**. Numpy Arrays

In [ ]:
import numpy as np
b = [1,2,3]
print(type(b))
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
[1,2,3]
[4,5,6]
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'list'>
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Create numpy arrays

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
#                        #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.46132095 0.58653583]
 [0.7897327  0.12477897]]


In [ ]:
mul = np.matmul(a,c)
mul

array([[0., 0.],
       [0., 0.]])

## **Section 5.1** Array Indexing

Slicing

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a.shape)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(b)
print(a[0, 1])   # Prints "77"

Mix integer and slice indexing

In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array.

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

## **Section 6:** Basic Pandas Concepts


In [ ]:
import pandas as pd

#### Create a simple DataFrame
DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

- syntax: pd.DataFrame({column1 : value1, column2 : value2, column3 : value3})

Values can be of any datatype. Only constraint is that each list should be of equal length

In [ ]:
df = pd.DataFrame({'name':['Bob','Jen','Tim'],
                   'age':[20,30,40],
                   'pet':['cat', 'dog', 'bird'],
                   'monthly_salary': [10000,20000,30000]})

df

name  age   pet  monthly_salary
0  Bob   20   cat           10000
1  Jen   30   dog           20000
2  Tim   40  bird           30000

In [ ]:
df.monthly_salary

0    10000
1    20000
2    30000
Name: monthly_salary, dtype: int64

#### View the column names and index values

The index is one of the most important concepts in pandas.

Each dataframe has only a single index which is always available as `df.index` and if you do not supply one (as we did not for this dataframe) a new one is made automatically.

Indexes define how to access rows of the dataframe.

The simplest index is the range index but there are more complex ones like interval index, datetime index and multi index.

In [ ]:
print(df.columns)
print(df.index)

Index(['name', 'age', 'pet', 'monthly_salary'], dtype='object')
RangeIndex(start=0, stop=3, step=1)


#### Select a column by name in 2 different ways

These two ways are equivalent and can be used interchangeably almost always.

In [ ]:
print(df['name'])
print(df.name)

0    Bob
1    Jen
2    Tim
Name: name, dtype: object
0    Bob
1    Jen
2    Tim
Name: name, dtype: object


**Caution:**
The primary exception is when the name of the column contains spaces. If for example we had a column called "monthly profit" we have to use `df['monthly profit']` because `df.monthly profit` is a syntactic error.

#### Select multiple columns

To select multiple columns we use `df[columns_to_select]` where `columns_to_select` are the columns we are interested in given as a simple python list. As the result we will get another data frame.

This is the equivalent of listing columns names in `SELECT` part of a sql query.

In [ ]:
df['name']

0    Bob
1    Jen
2    Tim
Name: name, dtype: object

In [ ]:
df[['name','pet','monthly_salary']]
# df

name   pet  monthly_salary
0  Bob   cat           10000
1  Jen   dog           20000
2  Tim  bird           30000

#### Select a row by index
We can always access any row in the dataframe using `.iloc[i]` for some integer i.

The result is a series object from which we can access values by using column indexing.

In [ ]:
df.iloc[1:2]

#**Assignment 1**

In [ ]:
# Dataset
sales = [100,130,119,92,35]
customer_account = ['B100','J101','X102','P103','R104']
city = ['BOS','LA','NYC','SF','CHI']

**Q1.** Create a DataFrame with the data above

In [ ]:
df2 = pd.DataFrame({'sales':sales,
                    'customer_account':customer_account,
                    'city':city})

**Q2.** What is the name of the first column?

**Q3.** Which customer is in the last row of the DataFrame?

**Q4.** Access all information of customer 'X102'

**Q5.** Print the first, 6th and last elements of the list [1,2,3,4,5,6,7,8,9,10] using list operations.

**Q6.** Print the elements from indices 3 to 6 of the list [1,2,3,4,5,6,7,8,9,10] using list slicing.

**Q7.** Write a function to check if the below variables are of integer variable type or string data type
x = 156
y = 'peter pan'
z = 'hello123'

You can use this as the starting point

def check_data_type(var):


  return

**Q7** Find the mean of the following numpy array named 'sample_array'

sample_array = np.random.random((5,5))